class HTTPStatusNot200Error < StandardError; end
class HTTP302FoundMovedError < StandardError; end
class HTTP400BadRequestError < StandardError; end
class HTTP401NotAuthorizedError < StandardError; end
class HTTP403ForbiddenError < StandardError; end
class HTTP404ResourceNotFoundError < StandardError; end
class HTTP405MethodNotAllowedError < StandardError; end
class HTTP413RequestEntitiyToLargeError < StandardError; end
class HTTP424FailedDependencyError < StandardError; end
class HTTP500InternalServerError < StandardError; end
class TooManyRetriesError < StandardError; end
class DeepRubyfiError < StandardError; end
class FGTPortNotOpenError < StandardError; end
class SafeModeActiveError < StandardError; end
class HTTPMethodUnknownError < StandardError; end
class CMDBPathError < StandardError; end
class CMDBNameError < StandardError; end
class CMDBMKeyError < StandardError; end
class CMDBChildNameError < StandardError; end
class CMDBChildMKeyError < StandardError; end