require 'fgt_rest_api'
require 'fgt_rest_api/ext/system'
require 'fgt_rest_api/ext/router'
require 'fgt_rest_api/ext/interface'
require 'fgt_rest_api/ext/ipsec'
require 'fgt_rest_api/ext/policy_and_object'
